
export const questions: string[] = [
    "What's a bad name for a boat?",
    "A word that shouldn't exist?",
    "What's the worst thing to say at a wedding?",
    "Your spirit animal, but it has to be an insect?",
    "The worst thing to hear from a pilot?",
    "A better name for 'feet'?",
    "What would you call a group of Karens?",
    "The most useless superpower?",
    "If you could rename 'sushi', what would you call it?",
    "A weird smell you secretly like?",
    "What's something you yell at your computer?",
    "An activity that is 10x better with music?",
    "What's a weird thing to have in your pocket?",
    "If you were a ghost, who would you haunt?",
    "A food that's seriously overrated?",
    "What's the opposite of a cat?",
    "The best topping for ice cream?",
    "One phrase to describe your last dream?",
    "A movie title that describes your life?",
    "What's a vegetable you just don't trust?",
    "What would you NOT do with a time machine?",
    "A secret your pet would tell about you?",
    "The worst sound in the world?",
    "What's a fictional character you'd avoid?",
    "The last thing you'd want to find in your burrito?",
    "A bad pickup line that might actually work?",
    "What's the most boring sport to watch?",
    "Something you'd do if you were invisible for a day?",
    "A terrible name for a new crayon color?",
    "What would you ask a psychic?",
    "If animals could talk, which would be the rudest?",
    "A product that needs a warning label but doesn't have one?",
    "What's a food you could eat for the rest of your life?",
    "A weird talent you have?",
    "What's something that's normal now but will be weird in 50 years?",
    "What's the best way to start an argument?",
    "A terrible theme for a party?",
    "What would you name your rock band?",
    "What's something you pretend to understand?",
    "A TV show you think is garbage?",
    "What's the most annoying phrase?",
    "Something you'd buy if you won the lottery?",
    "The worst advice you've ever received?",
    "If you had a warning label, what would it say?",
    "What's a conspiracy theory you could start?",
    "The last thing you'd want to be famous for?",
    "What's a household chore you secretly enjoy?",
    "What's a weird thing to collect?",
    "An alternate use for a fork?",
    "What's a boring fact about yourself?",
    "A terrible name for a new baby?",
    "Something you shouldn't lick?",
    "A terrible tagline for a hospital?",
    "A better name for a 'graveyard'?",
    "What do you call a sad cup of coffee?",
    "A weird thing to be a professional at?",
    "An animal you'd trust to do your taxes?",
    "What's something you'd find in a wizard's junk drawer?",
    "A ridiculous reason to be late for work?",
    "What's the secret password to get into heaven?",
    "A terrible flavor for toothpaste?",
    "What would a goose say if it could talk?",
    "A food that looks disgusting but tastes amazing?",
    "Your pirate name?",
    "The most boring place to go on vacation?",
    "Something you'd never want to see in your rear-view mirror?",
    "A bad name for a detective agency?",
    "What's the last thing a bug sees?",
    "A weird thing to whisper to someone?",
    "What's a good name for a pet rock?",
    "A terrible prize to win in a cereal box?",
    "What would you name your boat if you were rich?",
    "Something you'd find at the bottom of the ocean?",
    "The worst ingredient to put on a pizza?",
    "A sound that makes you irrationally angry?",
    "A terrible slogan for a dating app?",
    "What's a weird thing to be allergic to?",
    "An emotion that needs a new name?",
    "A terrible job for a robot?",
    "A movie title that describes your last bathroom trip?",
    "Something you should never say to your boss?",
    "A weird thing to have a collection of?",
    "What's a lame excuse for a ghost?",
    "The worst thing to say during a job interview?",
    "A bad name for a rock band?",
    "A weird place to fall asleep?",
    "What's a question you should never ask a genie?",
    "A better name for 'sunglasses'?",
    "What's the most annoying sound a person can make?",
    "A terrible theme for a child's birthday party?",
    "What's something that's surprisingly expensive?",
    "A bad catchphrase for a superhero?",
    "A weird thing to keep in your car's glove box?",
    "What would you do with a million rubber ducks?",
    "A terrible name for a brand of toilet paper?",
    "What's the opposite of a potato?",
    "A weird way to greet someone?",
    "What's the worst thing about being an adult?",
    "A food you could never eat again?",
    "A lame reason to call 911?",
    "A terrible gift for a wedding?",
    "What's a boring thing to dream about?",
    "A weird thing to be famous for?",
    "What would you name a pet T-Rex?",
    "A terrible last-minute Halloween costume?",
    "The worst piece of advice you've received?",
    "A weird thing to do in an elevator?",
    "What would you find in a squirrel's secret stash?",
    "A bad name for a perfume?"
];
